language: csharp
sudo: required  
dist: trusty  
mono: none
dotnet: 2.0.0
env:
  global:
    - ResolveNuGetPackageAssets=true
    - EnableNuGetPackageRestore=true
os:
  - linux
  - osx
solution: Afonsoft.Logger.sln
install:
  - dotnet restore
  - nuget restore Afonsoft.Logger.sln
script:
  - dotnet build