version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
max_jobs: 1
image: Visual Studio 2017
environment:
  EnableNuGetPackageRestore: true
  ResolveNuGetPackageAssets: true
services: iis
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
before_build:
- cmd: nuget.exe restore -verbosity detailed C:\projects\Afonsoft.Logger\Afonsoft.Logger.sln
build:
  verbosity: detailed